### ISSUE TITLE
The maximum amount of "slides" is 32704 (at least on 8x8).

### ISSUE THREAD

**Issue by ViliamVadocz** [PietroJomini/auri#1]
https://github.com/PietroJomini/auri/blob/8b07b6b66c34bf0558bc79687fcd4b4d6335b646/take4/src/tak.c#L277

I calculated the size of the action space for several board sizes:

```
 n    placements    spreads(real)    total(real)
  3           18              108            126
  4           32              448            480
  5           75             1500           1575
  6          108             4464           4572
  7          147            12348          12495
  8          192            32512          32704
  9          243            82620          82863
 10          300           204400         204700
 11          363           495132         495495
 12          432          1179072        1179504
 13          507          2768220        2768727
 14          588          6421744        6422332
 15          675         14744700       14745375
 16          768         33553408       33554176
 ```

What you call "slides" I call "spreads".

I gave an explanation on the TakTalk Discord server: https://discord.com/channels/176389490762448897/932765511358513204/1129188904386441306

You are invited to join it if you are not there yet! We have a #developers channel where we talk about bot-making, amonst other things. The invite link is this: https://discord.gg/5vqmD9qVwE

**Comment by PietroJomini** [comment]
This is incredibly helpful, thank you so much! I've been meaning to do the math for a while, but somehow never found the time. Also, `spreads` probably makes more sense as a name, I use `slides` quite a bit for everything haha

Regarding discord, thanks for the invite, I'm already there! I still consider this project an experiment, I've never shared it for this reason, but maybe I'll take a look around the old threads and see if I find some other ideas
